[package]
name = "wormsign"
version = "0.1.0"
edition = "2021"

[dependencies]
sha3 = "0.10.1"
chrono = "0.4.26"
users = "0.11.0"
toml = "0.8.19"
serde = { version = "1", features = ["derive"] }
rand_core = { version = "0.6.4",  default-features = false }
getrandom = {version = "0.2.10", features = ["js"], optional = true }
wasm-bindgen = { version = "0.2.87", optional = true }

[dependencies.rand]
version = "0.8.5"
features = ["getrandom"]

[features]
mode2 = []
mode3 = []
mode5 = []
aes = []
random_signing = []
